name: Validate install.sh
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-setup-on-ubuntu22:
    name: Run setup.sh on Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./test/test-ubuntu.sh
  validate-setup-on-macos-14:
    name: Run setup.sh on MacOs
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - run: ./test/test-macos.sh
